<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED><!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>]><context name="network" description="::1 Linux analog 5.15.92-v7l+ #1 SMP Wed Dec 6 08:52:11 UTC 2023 armv7l" ><context-attribute name="hw_model" value="0x0001 on Raspberry Pi 4 Model B Rev 1.4" /><context-attribute name="hw_carrier" value="Raspberry Pi 4 Model B Rev 1.4" /><context-attribute name="hw_mezzanine" value="0x0001" /><context-attribute name="hw_name" value="Raspberry Pi to Pmod/QuikEval/PSM Adapter" /><context-attribute name="hw_vendor" value="Analog Devices, Inc." /><context-attribute name="hw_serial" value="23a33bbc-84cb-40fc-977e-93e1f8803552" /><context-attribute name="dtoverlay" value="vc4-kms-v3d,rpi-adxl345,gpio-shutdown" /><context-attribute name="local,kernel" value="5.15.92-v7l+" /><context-attribute name="uri" value="ip:localhost" /><context-attribute name="ip,ip-addr" value="::1" /><device id="hwmon0" name="rpi_volt" ><channel id="in0" type="input" ><attribute name="lcrit_alarm" filename="in0_lcrit_alarm" value="0" /></channel></device><device id="iio:device0" name="adxl345" ><channel id="accel_z" type="input" ><attribute name="calibbias" filename="in_accel_z_calibbias" value="100" /><attribute name="raw" filename="in_accel_z_raw" value="334" /><attribute name="sampling_frequency" filename="in_accel_sampling_frequency" value="100.000000000" /><attribute name="scale" filename="in_accel_scale" value="0.038300" /></channel><channel id="accel_y" type="input" ><attribute name="calibbias" filename="in_accel_y_calibbias" value="100" /><attribute name="raw" filename="in_accel_y_raw" value="104" /><attribute name="sampling_frequency" filename="in_accel_sampling_frequency" value="100.000000000" /><attribute name="scale" filename="in_accel_scale" value="0.038300" /></channel><channel id="accel_x" type="input" ><attribute name="calibbias" filename="in_accel_x_calibbias" value="200" /><attribute name="raw" filename="in_accel_x_raw" value="192" /><attribute name="sampling_frequency" filename="in_accel_sampling_frequency" value="100.000000000" /><attribute name="scale" filename="in_accel_scale" value="0.038300" /></channel><attribute name="sampling_frequency_available" value="0.09765625 0.1953125 0.390625 0.78125 1.5625 3.125 6.25 12.5 25 50 100 200 400 800 1600 3200" /></device><device id="iio_sysfs_trigger" ><attribute name="add_trigger" value="ERROR" /><attribute name="remove_trigger" value="ERROR" /></device></context>