<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED><!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>]><context name="network" description="10.44.3.92 Linux analog 6.1.54-v7l+ #3472 SMP Thu Jan 25 16:22:37 CET 2024 armv7l" ><context-attribute name="hw_carrier" value="Raspberry Pi 4 Model B Rev 1.4" /><context-attribute name="dtoverlay" value="rpi-ltc2664,vc4-kms-v3d" /><context-attribute name="hw_model" value="0x0001 on Raspberry Pi 4 Model B Rev 1.4" /><context-attribute name="hw_mezzanine" value="0x0001" /><context-attribute name="hw_name" value="PMD-RPI-INTZ" /><context-attribute name="hw_vendor" value="Analog Devices, Inc." /><context-attribute name="hw_serial" value="13837e96-186d-45af-ac0b-e252c8d49a78" /><context-attribute name="local,kernel" value="6.1.54-v7l+" /><context-attribute name="uri" value="ip:analog.local" /><context-attribute name="ip,ip-addr" value="10.44.3.92" /><device id="hwmon0" name="rpi_volt" ><channel id="in0" type="input" ><attribute name="lcrit_alarm" filename="in0_lcrit_alarm" value="0" /></channel></device><device id="iio:device0" name="ltc2664" ><channel id="voltage2" type="output" ><attribute name="offset" filename="out_voltage2_offset" value="-32768" /><attribute name="powerdown" filename="out_voltage2_powerdown" value="0" /><attribute name="raw" filename="out_voltage2_raw" value="0" /><attribute name="raw_available" filename="out_voltage2_raw_available" value="[0 1 65535]" /><attribute name="scale" filename="out_voltage2_scale" value="0.305175781" /></channel><channel id="voltage0" type="output" ><attribute name="offset" filename="out_voltage0_offset" value="-32768" /><attribute name="powerdown" filename="out_voltage0_powerdown" value="1" /><attribute name="raw" filename="out_voltage0_raw" value="65208" /><attribute name="raw_available" filename="out_voltage0_raw_available" value="[0 1 65535]" /><attribute name="scale" filename="out_voltage0_scale" value="0.305175781" /></channel><channel id="voltage3" type="output" ><attribute name="offset" filename="out_voltage3_offset" value="-32768" /><attribute name="powerdown" filename="out_voltage3_powerdown" value="0" /><attribute name="raw" filename="out_voltage3_raw" value="16000" /><attribute name="raw_available" filename="out_voltage3_raw_available" value="[0 1 65535]" /><attribute name="scale" filename="out_voltage3_scale" value="0.305175781" /></channel><channel id="voltage1" type="output" ><attribute name="offset" filename="out_voltage1_offset" value="-32768" /><attribute name="powerdown" filename="out_voltage1_powerdown" value="0" /><attribute name="raw0" filename="out_voltage1_raw0" value="0" /><attribute name="raw1" filename="out_voltage1_raw1" value="0" /><attribute name="raw_available" filename="out_voltage1_raw_available" value="[0 1 65535]" /><attribute name="scale" filename="out_voltage1_scale" value="0.305175781" /><attribute name="symbol" filename="out_voltage1_symbol" value="0" /><attribute name="toggle_en" filename="out_voltage1_toggle_en" value="0" /></channel><attribute name="waiting_for_supplier" value="0" /><debug-attribute name="direct_reg_access" value="ERROR" /></device></context>